### ISSUE TITLE
can i use it for dopamine 

### ISSUE THREAD

**Issue by Mabdelwanis** [0xallie/rocketbootstrapfix#3]
hello 👋
thanks for all your great work 
i have question  please 
can i use it with dopamine rootless 
if yes what's instructions please ?
greetings.

**Comment by ghost** [comment]
No, you can't, this is only meant for rootful and XinaA15, since RocketBootstrap itself isn't updated for rootless.

**Comment by Mabdelwanis** [comment]
thanks and have good day
